// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhSPy1NZ9lWpcG6zkssDK6YGyDUqvoT0c',
    appId: '1:387690996746:web:8cc52f91ba796b65b6abf3',
    messagingSenderId: '387690996746',
    projectId: 'connectme-7ab22',
    authDomain: 'connectme-7ab22.firebaseapp.com',
    storageBucket: 'connectme-7ab22.firebasestorage.app',
    measurementId: 'G-1G3PCVQM6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd5NENP3v_owFlypGX9eTveQju8Nj66Ec',
    appId: '1:387690996746:android:86f0b32beda06c49b6abf3',
    messagingSenderId: '387690996746',
    projectId: 'connectme-7ab22',
    storageBucket: 'connectme-7ab22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NY8tbX9V2J1NWOBTh8Ph2S_NXsDD1Fw',
    appId: '1:387690996746:ios:4916f0f9937b7001b6abf3',
    messagingSenderId: '387690996746',
    projectId: 'connectme-7ab22',
    storageBucket: 'connectme-7ab22.firebasestorage.app',
    iosBundleId: 'com.example.connectMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_NY8tbX9V2J1NWOBTh8Ph2S_NXsDD1Fw',
    appId: '1:387690996746:ios:4916f0f9937b7001b6abf3',
    messagingSenderId: '387690996746',
    projectId: 'connectme-7ab22',
    storageBucket: 'connectme-7ab22.firebasestorage.app',
    iosBundleId: 'com.example.connectMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhSPy1NZ9lWpcG6zkssDK6YGyDUqvoT0c',
    appId: '1:387690996746:web:078d7c659365b9e5b6abf3',
    messagingSenderId: '387690996746',
    projectId: 'connectme-7ab22',
    authDomain: 'connectme-7ab22.firebaseapp.com',
    storageBucket: 'connectme-7ab22.firebasestorage.app',
    measurementId: 'G-WMKP37L4QZ',
  );

}